import Head from "next/head";
import { Header, Hero, Row } from "@/components";
import { GetServerSideProps } from "next";
import { API_REQUEST } from "@/services/api.service";
import { IMovie } from "@/interfaces/app.interface";
import { AuthContext } from "@/Context/auth.context";
import { useContext } from "react";

export default function Home({
  trending,
  topRated,
  tvTopRated,
  popular,
  documentary,
  fantasy,
  comedy,
  history,
}: HomeProps): JSX.Element {
  const { isLoading } = useContext(AuthContext);

  if (isLoading) return <>{null}</>;

  return (
    <div className="relative min-h-screen">
      <Head>
        <title>Home - Sammi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Header />
      <main className="relative pl-4 pb-24 lg:space-y-24 lg:pl-16">
        <Hero trending={trending} />
        <section>
          <Row title="Top-rated" movies={topRated} />

          <Row title="Tv Show" movies={tvTopRated} isBig={false} />

          <Row title="Popular" movies={popular} />
          <Row title="documentary" movies={documentary.reverse()} />
          <Row title="fantasy" movies={fantasy} />
          <Row title="comedy" movies={comedy.reverse()} />
          <Row title="history" movies={history} />
        </section>
      </main>
    </div>
  );
}

export const getServerSideProps: GetServerSideProps<HomeProps> = async () => {
  const trending = await fetch(API_REQUEST.trending).then((res) => res.json());
  const topRated = await fetch(API_REQUEST.top_rated).then((res) => res.json());
  const tvTopRated = await fetch(API_REQUEST.tv_top_rated).then((res) =>
    res.json()
  );
  const popular = await fetch(API_REQUEST.popular).then((res) => res.json());
  const documentary = await fetch(API_REQUEST.documentary).then((res) =>
    res.json()
  );
  const comedy = await fetch(API_REQUEST.comedy).then((res) => res.json());
  const fantasy = await fetch(API_REQUEST.fantasy).then((res) => res.json());
  const history = await fetch(API_REQUEST.history).then((res) => res.json());

  return {
    props: {
      trending: trending.results,
      topRated: topRated.results,
      tvTopRated: tvTopRated.results,
      popular: popular.results,
      documentary: documentary.results,
      comedy: comedy.results,
      fantasy: fantasy.results,
      history: history.results,
    },
  };
};

interface HomeProps {
  trending: IMovie[];
  topRated: IMovie[];
  tvTopRated: IMovie[];
  popular: IMovie[];
  documentary: IMovie[];
  comedy: IMovie[];
  fantasy: IMovie[];
  history: IMovie[];
}
